### ISSUE TITLE
Check notebooks after pyfar patch release 0.6.9

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/gallery#79]
- [x] Check DSP functionality (squeeze removed in pyfar 0.6.9)
- [x] Time variant filtering (disabeled getting and setting a subset of samples/frequencues with `__getitem__` and `__setitem__` (https://pyfar-gallery.readthedocs.io/en/latest/gallery/interactive/pyfar_filtering.html#Block-wise-filtering)

**Comment by mberz** [comment]
I've checked, the time variant filtering processes data by block-wise accessing `.time`, so the underlying numpy array.
